browser=chrome

execution=local

url=https://www.saucedemo.com

username=standard_user

password=secret_sauce

platform=Windows 11

browserVersion=latest

sauce.username=YOUR_SAUCE_USERNAME

sauce.accessKey=YOUR_SAUCE_ACCESS_KEY